version: "3"
services:

  web-api:
    build:
      context: ./web-api
    ports:
      - "8000:8000"
    depends_on:
      - postgres
  client:
    build:
      context: ./client
    depends_on:
      - web-api
  background:
    build:
      context: ./background
    depends_on:
      - web-api
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: danila
      POSTGRES_PASSWORD: danila_python
      POSTGRES_DB: db_web_api

    ports:
      - "5432:5432"

